apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdubud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdubud
  template:
    metadata:
      labels:
        app: fdubud
    spec:
      containers:
      - image: okteto.dev/fdubud:latest
        name: fdubud
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2c5e438f-ed3a-4766-ae11-87d67c674cb8"
        - name: Vless_Path
          value: "/vl2j9555"
        - name: Vmess_UUID
          value: "2c5e438f-ed3a-4766-ae11-87d67c674cb8"
        - name: Vmess_Path
          value: "/vm66f36"
        - name: Share_Path
          value: "/v2link"
